export const SERVICES = [
  {
    slug: "direccion-produccion-creativa",
    title: "Dirección y Producción Creativa",
    shortTitle: "Dirección Creativa",
    description: "Liderazgo creativo integral desde el concepto hasta la entrega. Idea, dirección y producción bajo un mismo mando.",
    icon: "✦",
  },
  {
    slug: "direccion-de-arte",
    title: "Dirección de Arte",
    shortTitle: "Dirección de Arte",
    description: "Decisiones visuales que comunican sin palabras. Fotografía, vídeo, gráfica: todo coherente con la marca.",
    icon: "◎",
  },
  {
    slug: "produccion-grafica",
    title: "Producción Gráfica",
    shortTitle: "Producción Gráfica",
    description: "Materiales impresos y digitales con la calidad que exigen las grandes marcas. POS, packaging, editorial.",
    icon: "▣",
  },
  {
    slug: "guion-edicion-video",
    title: "Guión y Edición de Vídeo",
    shortTitle: "Vídeo",
    description: "Del guión a la postproducción. Vídeos corporativos, de producto, campañas y contenido para plataformas.",
    icon: "▷",
  },
  {
    slug: "creacion-de-contenido",
    title: "Creación de Contenido",
    shortTitle: "Contenido",
    description: "Contenido que informa, convence y convierte. Editorial, social, digital: cada pieza con propósito.",
    icon: "◈",
  },
  {
    slug: "diseno-de-identidad",
    title: "Diseño de Identidad Corporativa",
    shortTitle: "Identidad",
    description: "Identidades visuales construidas sobre estrategia, no sobre intuición. Marca, sistema, aplicaciones.",
    icon: "◇",
  },
  {
    slug: "naming",
    title: "Naming",
    shortTitle: "Naming",
    description: "Nombres que posicionan, se recuerdan y sobreviven al tiempo. Proceso estratégico con validación lingüística y legal.",
    icon: "Aa",
  },
  {
    slug: "copywriting",
    title: "Copywriting",
    shortTitle: "Copywriting",
    description: "Textos que venden sin parecer que venden. Copy estratégico para web, campañas, packaging y todo lo que comunica.",
    icon: "✍",
  },
  {
    slug: "eventos-corporativos",
    title: "Producción de Eventos Corporativos",
    shortTitle: "Eventos",
    description: "Convenciones, lanzamientos, incentivos y team buildings que generan impacto real. Producción integral sin fisuras.",
    icon: "◉",
  },
  {
    slug: "estrategia-de-comunicacion",
    title: "Estrategia de Comunicación",
    shortTitle: "Estrategia",
    description: "Antes de ejecutar, pensamos. Análisis, posicionamiento, plan de comunicación y métricas de éxito.",
    icon: "⊕",
  },
  {
    slug: "activacion-de-marca",
    title: "Activación de Marca",
    shortTitle: "Activaciones",
    description: "Experiencias en el punto de venta, street marketing y acciones que conectan la marca con el consumidor.",
    icon: "◈",
  },
  {
    slug: "marketing-digital",
    title: "Marketing Digital",
    shortTitle: "Marketing Digital",
    description: "Performance, paid media, SEO, social y automatizaciones integradas en la estrategia global de comunicación.",
    icon: "⊞",
  },
  {
    slug: "ia-y-automatizaciones",
    title: "IA y Automatizaciones",
    shortTitle: "IA",
    description: "Procesos inteligentes para agencias y empresas. Automatización de workflows, integración de IA y eficiencia operativa.",
    icon: "⊗",
  },
];

export const SECTORS = [
  {
    slug: "farmaceutico-salud",
    title: "Farmacéutico y Salud",
    description: "Comunicación regulada para marcas de salud, laboratorios y healthcare. Novartis, Alcon, ISDIN, Ipsen Farma.",
  },
  {
    slug: "gran-consumo-retail",
    title: "Gran Consumo y Retail",
    description: "Estrategia y activación para marcas de gran consumo, distribución y punto de venta. Coca-Cola, Haribo, Orbit.",
  },
  {
    slug: "lujo-premium",
    title: "Lujo y Premium",
    description: "Comunicación para marcas de lujo, moda y lifestyle premium. Chopard, Glenfiddich, Philipp Plein, Carolina Herrera.",
  },
  {
    slug: "tecnologia-b2b",
    title: "Tecnología y B2B",
    description: "Comunicación técnica y corporativa para empresas de tecnología y servicios B2B. SAP, GFT, Applus, Walk Me.",
  },
  {
    slug: "automocion",
    title: "Automoción",
    description: "Eventos y activaciones para marcas de automoción con estándares de excelencia internacionales. Porsche.",
  },
  {
    slug: "hosteleria-turismo",
    title: "Hostelería y Turismo",
    description: "Comunicación y eventos para cadenas hoteleras y operadores turísticos. Meliá, Avianca.",
  },
  {
    slug: "alimentacion-bebidas",
    title: "Alimentación y Bebidas",
    description: "Branding, packaging, activaciones y eventos para marcas de food & beverage. Perrier, Glenfiddich, Petit Farm.",
  },
];

export const CASES = [
  {
    slug: "alcon-air-optix-paneuropeo",
    client: "Alcon",
    title: "Roadshow paneuropeo Air Optix en 8 países",
    description: "Lanzamiento paneuropeo con app de realidad aumentada y gira por 8 ciudades.",
    services: ["Eventos", "Activación", "Tecnología"],
    sector: "Farmacéutico",
    results: "8 ciudades, 1 app de realidad aumentada, +2.000 profesionales impactados",
    videoUrl: "/videos/alcon-air-optix.mp4",
  },
  {
    slug: "sap-partner-summit",
    client: "SAP",
    title: "SAP Partner Summit para 250 participantes",
    description: "Convención internacional con producción integral para 250 partners de SAP.",
    services: ["Eventos", "Producción", "Contenido"],
    sector: "Tecnología",
    results: "250 participantes internacionales, producción AV integral, 98% satisfacción",
    videoUrl: "/videos/sap-partner-summit.mp4",
  },
  {
    slug: "coca-cola-grandvalira",
    client: "Coca-Cola",
    title: "Street marketing en Grandvalira para Coca-Cola",
    description: "Acción de guerrilla en la estación de esquí más grande de los Pirineos.",
    services: ["Street Marketing", "Activación", "Logística"],
    sector: "Gran Consumo",
    results: "Andorra + Madrid + Medellín, 3 mercados simultáneos",
    videoUrl: "/videos/coca-cola-grandvalira.mp4",
  },
  {
    slug: "puig-brand-ambassadors",
    client: "Puig",
    title: "Convención de 208 Brand Ambassadors: Puig",
    description: "Convención para embajadores de marca de las fragancias Puig en Barcelona.",
    services: ["Eventos", "Producción", "Formación"],
    sector: "Lujo",
    results: "208 asistentes, producción integral, activación de fragancias en directo",
    videoUrl: "/videos/puig-brand-ambassadors.mp4",
  },
  {
    slug: "novartis-certican-360",
    client: "Novartis",
    title: "Campaña 360° Certican: Novartis",
    description: "Campaña integral de producto farmacéutico con materiales para todos los canales.",
    services: ["Estrategia", "Creatividad", "Producción Gráfica"],
    sector: "Farmacéutico",
    results: "Campaña 360°, materiales para 6 canales, distribución nacional",
  },
  {
    slug: "meliá-60-aniversario",
    client: "Meliá Hotels",
    title: "60 Aniversario de Meliá Hotels International",
    description: "Evento corporativo de celebración para el 60 aniversario de la cadena hotelera.",
    services: ["Eventos", "Producción Creativa", "Logística"],
    sector: "Hostelería",
    results: "Evento corporativo emblemático, producción AV de alto nivel",
  },
  {
    slug: "chopard-elearning",
    client: "Chopard",
    title: "E-learning global para embajadores de fragancia Chopard",
    description: "Plataforma de formación interactiva para los embajadores de las fragancias Chopard a nivel mundial.",
    services: ["E-learning", "Contenido", "Diseño UX/UI"],
    sector: "Lujo",
    results: "Formación global, plataforma propia, contenido en varios idiomas",
  },
  {
    slug: "haribo-activacion",
    title: "Activación Haribo en grandes superficies con app",
    client: "Haribo",
    description: "Campaña de activación en el punto de venta con app gamificada para Haribo en grandes superficies.",
    services: ["Activación", "Digital", "POS"],
    sector: "Gran Consumo",
    results: "Activación en grandes superficies + app, +50.000 interacciones",
  },
  {
    slug: "applus-mwc",
    client: "Applus",
    title: "Stand y activación Applus en Mobile World Congress",
    description: "Diseño, construcción y gestión del stand de Applus en el Mobile World Congress de Barcelona.",
    services: ["Eventos", "Diseño", "Producción"],
    sector: "Tecnología",
    results: "Stand MWC, Family Day corporativo, presencia en 4YFN",
  },
  {
    slug: "metaembalatges-branding",
    client: "Metaembalatges",
    title: "Branding integral: Metaembalatges",
    description: "Identidad corporativa, web, fotografía y vídeo para empresa industrial de packaging.",
    services: ["Identidad", "Web", "Fotografía", "Vídeo"],
    sector: "Industrial",
    results: "Identidad completa, web + foto + vídeo, posicionamiento premium industrial",
  },
  {
    slug: "alcon-astigmatismo-campana",
    client: "Alcon",
    title: "Campaña de divulgación: Astigmatismo Alcon",
    description: "Dirección creativa integral para la campaña de divulgación sobre astigmatismo de Alcon.",
    services: ["Dirección Creativa", "Campaña Gráfica", "Producción Visual"],
    sector: "Farmacéutico",
    results: "Campaña de divulgación, dirección creativa integral, materiales visuales y foto",
  },
  {
    slug: "novartis-transplant-tomorrow",
    client: "Novartis",
    title: "Transplant Tomorrow: Mañana Empieza Hoy",
    description: "Concepto creativo, campaña gráfica, eventos y vídeo para el programa Transplant Tomorrow de Novartis.",
    services: ["Concepto Creativo", "Campaña Gráfica", "Eventos", "Vídeo"],
    sector: "Farmacéutico",
    results: "Concepto integral, campaña gráfica, producción de eventos y vídeo corporativo",
  },
  {
    slug: "ergobaby-orbit-packaging",
    client: "Ergobaby",
    title: "Packaging y material POS: Ergobaby Orbit",
    description: "Diseño gráfico de packaging y material en punto de venta para la línea Orbit de Ergobaby.",
    services: ["Diseño Gráfico", "Packaging", "Material POS"],
    sector: "Gran Consumo",
    results: "Sistema de packaging y POS diseñado e implementado para mercado europeo",
  },
  {
    slug: "gft-mwc-4yfn",
    client: "GFT",
    title: "Stand MWC y 4YFN: GFT",
    description: "Diseño y producción del stand de GFT en el Mobile World Congress y el 4 Years From Now de Barcelona.",
    services: ["Diseño de Stand", "Producción", "Eventos"],
    sector: "Tecnología",
    results: "Stand diferenciado en MWC y presencia en 4YFN, generación de leads cualificados",
  },
  {
    slug: "porsche-interclassics-brussels",
    client: "Porsche",
    title: "Stand InterClassics Brussels: Porsche",
    description: "Diseño y producción del stand de Porsche en la feria InterClassics de Bruselas.",
    services: ["Diseño de Stand", "Producción", "Eventos"],
    sector: "Automoción",
    results: "Stand de alta gama para el evento de referencia del automovilismo clásico europeo",
  },
  {
    slug: "carolina-herrera-desfile-ss2026",
    client: "Carolina Herrera",
    title: "Desfile Carolina Herrera",
    description: "Producción ejecutiva del desfile de Carolina Herrera para la colección primavera-verano 2026.",
    services: ["Producción Ejecutiva", "Eventos", "Logística"],
    sector: "Lujo",
    results: "Producción ejecutiva del desfile SS2026 de Carolina Herrera",
  },
  {
    slug: "gogreen-expositor-pos",
    client: "GoGreen",
    title: "Expositor POS: GoGreen",
    description: "Diseño gráfico y producción de expositor en punto de venta para GoGreen.",
    services: ["Diseño Gráfico", "Material POS", "Producción Gráfica"],
    sector: "Gran Consumo",
    results: "Expositor POS diseñado y producido para implantación en retail",
  },
  {
    slug: "stingbye-packaging",
    client: "StingBye",
    title: "Diseño de packaging: StingBye",
    description: "Dirección de arte y diseño gráfico del packaging para la marca StingBye.",
    services: ["Dirección de Arte", "Diseño Gráfico", "Packaging"],
    sector: "Gran Consumo",
    results: "Sistema de packaging completo diseñado para lanzamiento de producto",
  },
];

export const SOLUTIONS = [
  {
    slug: "lanzamiento-de-producto",
    title: "Lanzamiento de Producto",
    description: "De la idea al mercado con estrategia, creatividad y producción integradas. Sin intermediarios, sin pérdidas de tiempo.",
  },
  {
    slug: "convenciones-y-eventos",
    title: "Convenciones y Eventos Corporativos",
    description: "Convenciones, incentivos, team buildings y eventos de lanzamiento. Producción integral para audiencias exigentes.",
  },
  {
    slug: "identidad-corporativa-web",
    title: "Identidad Corporativa y Web",
    description: "De la estrategia de naming al sistema de identidad completo, web incluida. Todo bajo el mismo criterio creativo.",
  },
  {
    slug: "campana-comunicacion-integral",
    title: "Campaña de Comunicación Integral",
    description: "Estrategia, creatividad, producción y distribución. Campaña 360° que funciona en todos los canales.",
  },
  {
    slug: "activacion-punto-de-venta",
    title: "Activación en Punto de Venta",
    description: "Street marketing, POS, promotores, experiencias de marca en retail y grandes superficies.",
  },
  {
    slug: "formacion-corporativa-elearning",
    title: "Formación Corporativa y E-learning",
    description: "Plataformas de formación interactiva, e-learnings y programas de onboarding para equipos globales.",
  },
];

export const BLOG_POSTS = [
  {
    slug: "que-es-una-agencia-de-comunicacion-integral",
    title: "Qué es una agencia de comunicación integral y por qué lo necesitas",
    description: "La diferencia entre contratar especialistas aislados y trabajar con una agencia que piensa, produce y activa de forma coordinada.",
    date: "2024-01-15",
    category: "Estrategia",
    readingTime: 8,
  },
  {
    slug: "como-organizar-una-convencion-corporativa",
    title: "Cómo organizar una convención corporativa sin perder la cabeza",
    description: "Guía práctica para directores de marketing y comunicación que tienen que producir un evento corporativo de alto nivel.",
    date: "2024-02-01",
    category: "Eventos",
    readingTime: 10,
  },
  {
    slug: "identidad-corporativa-vs-imagen-corporativa",
    title: "Identidad corporativa vs imagen corporativa: no es lo mismo",
    description: "Por qué muchas empresas confunden los dos conceptos y cómo afecta esto a su posicionamiento y percepción de marca.",
    date: "2024-02-15",
    category: "Branding",
    readingTime: 7,
  },
  {
    slug: "street-marketing-que-funciona",
    title: "Street marketing que funciona: casos reales y lecciones aprendidas",
    description: "Análisis de campañas de street marketing exitosas, qué tienen en común y cómo replicar los elementos que generan impacto.",
    date: "2024-03-01",
    category: "Activaciones",
    readingTime: 9,
  },
  {
    slug: "estrategia-comunicacion-farma",
    title: "Estrategia de comunicación en el sector farmacéutico: guía para no equivocarse",
    description: "Comunicar en el sector farma exige precisión, cumplimiento normativo y creatividad dentro de márgenes muy estrechos.",
    date: "2024-03-15",
    category: "Sectores",
    readingTime: 11,
  },
  {
    slug: "naming-proceso-crear-nombre-marca",
    title: "Naming: el proceso completo para crear el nombre de una marca",
    description: "Desde el briefing hasta la validación legal. Cómo funciona un proyecto de naming profesional y por qué no debe hacerse de prisa.",
    date: "2024-04-01",
    category: "Branding",
    readingTime: 8,
  },
  {
    slug: "video-corporativo-roi",
    title: "Vídeo corporativo con ROI: cómo medir el impacto real del audiovisual",
    description: "El vídeo no es solo imagen. Métricas, estrategias de distribución y tipos de producción que generan retorno medible.",
    date: "2024-04-15",
    category: "Contenido",
    readingTime: 9,
  },
  {
    slug: "activacion-de-marca-punto-de-venta",
    title: "Activación de marca en el punto de venta: qué hay que tener en cuenta",
    description: "POS, promotores, displays, eventos en tienda: guía para planificar una activación de marca en retail que convierta.",
    date: "2024-05-01",
    category: "Activaciones",
    readingTime: 8,
  },
  {
    slug: "comunicacion-b2b-diferente-b2c",
    title: "Por qué la comunicación B2B es diferente (y cómo hacerlo bien)",
    description: "Ciclos de venta largos, múltiples stakeholders y decisiones racionales: cómo adaptar la estrategia de comunicación a entornos B2B.",
    date: "2024-05-15",
    category: "Estrategia",
    readingTime: 10,
  },
  {
    slug: "produccion-eventos-internacionales",
    title: "Producción de eventos internacionales: logística, cultura y contingencias",
    description: "Producir un evento fuera de España exige más que un buen proveedor local. Todo lo que hay que prever antes de cruzar fronteras.",
    date: "2024-06-01",
    category: "Eventos",
    readingTime: 12,
  },
  {
    slug: "diseno-identidad-marcas-lujo",
    title: "Diseño de identidad para marcas de lujo: menos es más, pero el menos debe ser perfecto",
    description: "Los estándares de las marcas premium en diseño gráfico. Qué distingue una identidad de lujo y cómo se construye.",
    date: "2024-06-15",
    category: "Branding",
    readingTime: 9,
  },
  {
    slug: "elearning-corporativo-que-funciona",
    title: "E-learning corporativo que la gente completa de verdad",
    description: "El 80% de los e-learnings corporativos se abandonan a mitad. Qué hace que la formación digital funcione.",
    date: "2024-07-01",
    category: "Formación",
    readingTime: 8,
  },
  {
    slug: "copywriting-b2b-guia-practica",
    title: "Copywriting B2B: guía práctica para comunicar valor sin aburrir",
    description: "Los textos B2B no tienen por qué ser aburridos. Cómo escribir para personas que toman decisiones de compra complejas.",
    date: "2024-07-15",
    category: "Contenido",
    readingTime: 10,
  },
  {
    slug: "tendencias-comunicacion-corporativa-2025",
    title: "Tendencias en comunicación corporativa para 2025",
    description: "Qué está cambiando en la forma en que las empresas se comunican: IA, autenticidad, integración y la vuelta a lo presencial.",
    date: "2024-08-01",
    category: "Tendencias",
    readingTime: 9,
  },
  {
    slug: "como-elegir-agencia-comunicacion",
    title: "Cómo elegir una agencia de comunicación: lo que nadie te dice",
    description: "Las preguntas que tienes que hacer antes de firmar. Señales de alarma y señales positivas en una primera reunión con una agencia.",
    date: "2024-08-15",
    category: "Estrategia",
    readingTime: 8,
  },
  {
    slug: "ia-en-comunicacion-corporativa",
    title: "IA en comunicación corporativa: lo que ya funciona y lo que todavía no",
    description: "Aplicaciones reales de la inteligencia artificial en agencias de comunicación. Qué automatizar, qué no delegar nunca a una máquina.",
    date: "2024-09-01",
    category: "Tendencias",
    readingTime: 10,
  },
];
